name: comp23
channels:
  - conda-forge
  - defaults
dependencies:
  - asttokens=2.4.0=pyhd8ed1ab_0
  - attrs=23.1.0=pyh71513ae_1
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.5=pyhd8ed1ab_0
  - blosc=1.21.5=hdccc3a2_0
  - brotli-python=1.1.0=py39h99910a6_0
  - bzip2=1.0.8=h8ffe710_4
  - ca-certificates=2023.7.22=h56e8100_0
  - certifi=2023.7.22=pyhd8ed1ab_0
  - cftime=1.6.2=py39hc266a54_1
  - charset-normalizer=3.2.0=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.1.4=pyhd8ed1ab_0
  - debugpy=1.8.0=py39h99910a6_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - exceptiongroup=1.1.3=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - hdf4=4.2.15=h1334946_6
  - hdf5=1.14.2=nompi_h73e8ff5_100
  - idna=3.4=pyhd8ed1ab_0
  - importlib-metadata=6.8.0=pyha770c72_0
  - importlib_metadata=6.8.0=hd8ed1ab_0
  - importlib_resources=6.1.0=pyhd8ed1ab_0
  - intel-openmp=2023.2.0=h57928b3_49496
  - ipykernel=6.25.2=pyh60829e3_0
  - ipython=8.15.0=pyh5737063_0
  - jedi=0.19.0=pyhd8ed1ab_0
  - jsonschema=4.19.1=pyhd8ed1ab_0
  - jsonschema-specifications=2023.7.1=pyhd8ed1ab_0
  - jupyter_client=8.3.1=pyhd8ed1ab_0
  - jupyter_core=5.3.1=py39hcbf5309_0
  - krb5=1.21.2=heb0366b_0
  - libaec=1.0.6=h63175ca_1
  - libblas=3.9.0=18_win64_mkl
  - libcblas=3.9.0=18_win64_mkl
  - libcurl=8.3.0=hd5e4a3a_0
  - libffi=3.4.2=h8ffe710_5
  - libhwloc=2.9.2=default_haede6df_1009
  - libiconv=1.17=h8ffe710_0
  - libjpeg-turbo=2.1.5.1=hcfcfb64_1
  - liblapack=3.9.0=18_win64_mkl
  - libnetcdf=4.9.2=nompi_h8284064_112
  - libsodium=1.0.18=h8d14728_1
  - libsqlite=3.43.0=hcfcfb64_0
  - libssh2=1.11.0=h7dfc565_0
  - libxml2=2.11.5=hc3477c8_1
  - libzip=1.10.1=h1d365fa_3
  - libzlib=1.2.13=hcfcfb64_5
  - lz4-c=1.9.4=hcfcfb64_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mkl=2022.1.0=h6a75c08_874
  - nbformat=5.9.2=pyhd8ed1ab_0
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - netcdf4=1.6.4=nompi_py39h9a3bb69_102
  - numpy=1.26.0=py39hddb5d58_0
  - openssl=3.1.3=hcfcfb64_0
  - packaging=23.1=pyhd8ed1ab_0
  - pandas=2.1.0=py39h32e6231_0
  - parso=0.8.3=pyhd8ed1ab_0
  - patsy=0.5.3=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pip=23.2.1=pyhd8ed1ab_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_1
  - platformdirs=3.10.0=pyhd8ed1ab_0
  - plotly=5.17.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.39=pyha770c72_0
  - prompt_toolkit=3.0.39=hd8ed1ab_0
  - psutil=5.9.5=py39ha55989b_0
  - pthreads-win32=2.9.1=hfa6e2cd_3
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pygments=2.16.1=pyhd8ed1ab_0
  - pysocks=1.7.1=pyh0701188_6
  - python=3.9.18=h4de0772_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.18.1=pyhd8ed1ab_0
  - python-tzdata=2023.3=pyhd8ed1ab_0
  - python_abi=3.9=3_cp39
  - pytz=2023.3.post1=pyhd8ed1ab_0
  - pywin32=304=py39h99910a6_2
  - pyzmq=25.1.1=py39hea35a22_0
  - referencing=0.30.2=pyhd8ed1ab_0
  - requests=2.31.0=pyhd8ed1ab_0
  - rpds-py=0.10.6=py39hf21820d_0
  - scipy=1.11.3=py39hddb5d58_1
  - setuptools=68.2.2=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.1.10=hfb803bf_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - statsmodels=0.14.0=py39hd88c2e4_2
  - tbb=2021.10.0=h91493d7_0
  - tenacity=8.2.3=pyhd8ed1ab_0
  - tk=8.6.12=h8ffe710_0
  - tornado=6.3.3=py39ha55989b_0
  - traitlets=5.10.0=pyhd8ed1ab_0
  - typing-extensions=4.8.0=hd8ed1ab_0
  - typing_extensions=4.8.0=pyha770c72_0
  - tzdata=2023c=h71feb2d_0
  - ucrt=10.0.22621.0=h57928b3_0
  - urllib3=2.0.4=pyhd8ed1ab_0
  - vc=14.3=h64f974e_17
  - vc14_runtime=14.36.32532=hdcecf7f_17
  - vs2015_runtime=14.36.32532=h05e6639_17
  - wcwidth=0.2.6=pyhd8ed1ab_0
  - wheel=0.41.2=pyhd8ed1ab_0
  - win_inet_pton=1.1.0=pyhd8ed1ab_6
  - xarray=2023.8.0=pyhd8ed1ab_0
  - xz=5.2.6=h8d14728_0
  - zeromq=4.3.4=h0e60522_1
  - zipp=3.16.2=pyhd8ed1ab_0
  - zlib=1.2.13=hcfcfb64_5
  - zstd=1.5.5=h12be248_0
prefix: C:\Users\jb593c\Anaconda3\envs\comp23
